spring:
    jpa:
        hibernate:
            naming:
                implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
                physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
            ddl-auto: update

        show-sql: true
        database: mysql
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        properties:
            hibernate:
                format_sql: true


    datasource:
        username: kakao
        password: kakao
        url: jdbc:mysql://localhost:3306/kakao?characterEncoding=UTF-8&serverTimezone=UTC
        driver-class-name: com.mysql.cj.jdbc.Driver

    jackson:
        property-naming-strategy: SNAKE_CASE
    http:
        encoding:
            charset: UTF-8
            enabled: true
            force: true

    servlet:
        multipart:
            max-file-size: 128KB
            max-request-size: 128KB

server:
    port: 8080
